dist: trusty
addons:
  apt:
    packages:
    - libsecret-1-dev
language: node_js
node_js:
- 12.14.1
script:
- npx fitbit-build
deploy:
  edge: true
  provider: releases
  file: build/app.fba
  on:
    tags: true
  token:
    secure: Udzuy9pSHmP1PpfIcjzfFaS7McWqQU/oOWcANO7n5cMokeGHcH/iIdxpz7+a1USr4X99hfRBAtO+WI0B2mIa8B9Jj5RFZ1+sqhH1BTlO1hMh9fYlJGtuzGFzM2vv0yFBiSOyIpG+wuvfcHd22fnSzxUKFfn9lSb7u7sHvUK0tmez2i7lyOUgoQbkhDf6q4UP6rg+hjYi+IeZsvoPFnM0QMCaHp/WBMbI66ZITugCmJgGZ2sqzcrenShqTZI8L+4BgD2CzPHOgmqf6Pqx2yujZsZbyzCO4YVdAxMNaQ7VMZ+IB9kJJbwvzlynYc7YuMjUiQ7KPPvTQWkX+zjuZ9hA0gbCSzdYz1aje1dCJg8OHbvfpwQEdwT46ja2RxuBIbJOkViGx2lFhV6DVs4/YJ52KIRz2q7610sAKcR5KZ5u1Jt4lwFsF6GPHPF7N6xg5FsXkpyhIdHoz6PtaDQJ3eQjr03FD5Olzna3kQMQJSSfzrYHGkld+LvNY1FR92fYbCRXc1lS6cBNk3BLF6A/mLVxHsVZxkH/7EkK4UEvOteRPLOCggx3ECg32+86TuepMmpM/2nieLnQSwhJwfYZoG1kSTrVz85BSyjQ20Rf+xN7bW76y9WQ8Vlo0KuZE43KV3+q6NfCagiadtZLVx1YHh8F4+iCpJeGX4XRWytYhPI/oxs=
