dist: trusty
addons:
  apt:
    packages:
    - libsecret-1-dev
language: node_js
node_js:
- 12.14.1
script:
- npx fitbit-build
deploy:
  provider: releases
  api_key:
    secure: eLKycw7lODxWGtbzxzaAkW83gBFYAzdCVZUyB/WgUB/fN2KWgA7KTqGCsY6TafS/59+/VX03vq/qCet54ZOPcPMFL52ednRGveCDjtDuqx47vY000JIeWjxXq1dfsRKyDw/yfNLB0A7EuntyNIEmcXgP5BpujWoUB8h8jF7fvj7ZTPECd24Pd2q/g/hc4Jj7GI5sq4mwXtHr0IWY9ykHaLHjDjZ67T1/9sK86wCb2IdvkT9nrBweWO0lQKLyn7va3zxsPFHFsj2ryZAKFbOp7KYDXpuXNtC2YY1oO+wUfXuAxeb3nDhKW4lqIJR6EYJyDRx3zooodxcAH8Kp6lMzZnqVGAT9hS0rAjHta1svwFRx85zDpqPJRhgDhp17hmmAiHCA98Q+DvuQDgKyGmH5Iii3I9qyN6NHJTiLSHKhALaC3fV2t56k3n2B4OANVSbjUgsXCAnXRHPlEiuQGnLBXo6/Ulvk8iF7KKG4LMFaJAMemVyDxysShDHndqLpeOodHZPFWxOE/2lqNrYXhPXiywMvzSZ9MW7nPgyJ1gyS0UqkpXtiYm21oaeXVZ424Q/TIXBBnecTbTbWGxO8UdSApBBlS2s2dmaQ04WTFv9G0f9Cn+ZUFc249XrorRAzj/E3uIphcioesymjH3Yab973bIdRBZCWq2B2HJd2F/E8FKo=
  file: build/app.fba
  on:
    tags: true
    repo: ogerardin/fitbit-luxparking
