dist: trusty
addons:
  apt:
    packages:
    - libsecret-1-dev
language: node_js
node_js:
- 12.14.1
script:
- npx fitbit-build
deploy:
  edge: true
  provider: releases
  on:
    tags: true
  file: build/app.fba
  token:
    secure: aeNerK7FSqCwJXx7Qvn9WNCtgzf8AzwoT5f3NqHej7VHuVymZywSDLSND9EMwcBYU4RoaOwpmIXpJ/O1hoZ7SRXkXGJ7NHI8LY94du6pNGsK0G0F+IlMQtzD83VmEGuN2942kL3iUgaeF5abvelsXHSow5wJtB2EQHwiOGFsxZ7M6Ck1GF6NVXrYtn1ZJIfLpqBe2zqgMPIOzwJEkK5CPxRnevM35p+u/sb9Sv5Uqvrv0HDkpohp8JUj5Z8fHV56yXFAwTxy3S6Z3TL8is0YRDLgLmtu5826KgQm7oy1CDq6BUvHzn5ujSD2zeI1+wWt3xczmiVJf0OWMLpWVi2kyyRqoQdQyqG3LIcvNv8z95yVEgEhUyoeSxBRs+ZFl2VggKQ5tp9foEgqLjkS96jvNB/B2e8ZpBfCRObNPmtvHPRn2Gi+/9+2ZETnrRDSdyMDaieSJvtoDLeIzYThFNAQRd5hmEb1ZELHJ2iRF5vEtEfwTGlVgqOB6AxNdJpxcn266qx3woFymfu1pHZPGqPF0PHzGZ9fljqNQia0S/4DepSuBHk0g2Xob53JnCGrsisxoczXab/9zXuzwgSlV4gPYq9Y1g9GuF5uNDcnPP+1FynTtqH3iv5hhjUXvX6LhYVsfHXfyKhmxYaM85UKbiTtYP/y/nVkxUry15IZhLA4eKw=
